// Generated by CoffeeScript 1.9.3
(function() {
  var QuadTree, expect;

  expect = require('chai').expect;

  QuadTree = require('../lib/QuadTree');

  describe('QuadTree Tests', function() {
    var o1, qt, r1;
    qt = new QuadTree({
      x: -100,
      y: -100,
      width: 200,
      height: 200
    }, 5);
    r1 = {
      x: 0,
      y: 0,
      width: 10,
      height: 10
    };
    o1 = {
      x: 0,
      y: 0,
      width: 10,
      height: 10,
      id: 17
    };
    it('should be able to insert and retrieve an object', function() {
      var test;
      qt.insert(o1);
      test = qt.retrieve(r1)[0];
      return expect(test.id).to.equal(o1.id);
    });
    it('should be able to insert and retrieve a number of objects that is larger than maxobject', function() {
      var i, j, o, r, succeed, testarr, x, y;
      testarr = [];
      succeed = false;
      for (i = j = 1; j <= 20; i = ++j) {
        x = parseInt(Math.random() * 200) - 100;
        y = parseInt(Math.random() * 200) - 100;
        o = {
          x: x,
          y: y,
          width: 10,
          height: 10,
          id: i
        };
        r = {
          x: x,
          y: y,
          width: 10,
          height: 10
        };
        testarr.push({
          o: o,
          r: r
        });
        qt.insert(o);
      }
      testarr.forEach(function(test) {
        var result;
        result = qt.retrieve(test.r);
        return result.forEach((function(_this) {
          return function(res) {
            if (res.id === test.o.id) {
              return succeed = true;
            }
          };
        })(this));
      });
      return expect(succeed).to.equal(true);
    });
    it('should be able to insert and remove an object', function() {
      var o2, r2, result;
      r2 = {
        x: 5,
        y: 2,
        width: 10,
        height: 10
      };
      o2 = {
        x: 5,
        y: 2,
        width: 10,
        height: 10,
        id: 4711
      };
      qt.insert(o2);
      qt.remove(r2);
      result = qt.retrieve(r2);
      return expect(result.length).to.equal(0);
    });
    it('should be able to insert a large object in a split tree and verify it stays in the top node', function() {
      var exists, i, j, o, o3, r, r3, succeed, testarr, x, y;
      testarr = [];
      succeed = false;
      for (i = j = 1; j <= 20; i = ++j) {
        x = parseInt(Math.random() * 100);
        y = parseInt(Math.random() * 100);
        o = {
          x: x,
          y: y,
          width: 10,
          height: 10,
          id: i
        };
        r = {
          x: x,
          y: y,
          width: 10,
          height: 10
        };
        testarr.push({
          o: o,
          r: r
        });
        qt.insert(o);
      }
      r3 = {
        x: -50,
        y: -50,
        width: 100,
        height: 100
      };
      o3 = {
        x: -50,
        y: -50,
        width: 100,
        height: 100,
        id: 111
      };
      qt.insert(o3);
      exists = false;
      qt.objects.forEach(function(oo) {
        if (oo.id === 111) {
          return exists = true;
        }
      });
      return expect(exists).to.equal(true);
    });
    return it('should be able to collide two overlapping rects', function() {
      var collissions, exists, o2;
      o1 = {
        x: 0,
        y: 0,
        width: 10,
        height: 10,
        id: 176
      };
      o2 = {
        x: -5,
        y: -5,
        width: 10,
        height: 10,
        id: 4712
      };
      qt.insert(o1);
      qt.insert(o2);
      collissions = qt.getCollissionsFor(o1);
      exists = false;
      collissions.forEach(function(oo) {
        if (oo.id === 4712) {
          return exists = true;
        }
      });
      return expect(exists).to.equal(true);
    });
  });

}).call(this);

//# sourceMappingURL=qt-spec.js.map
